fuji: vintf: Add missing specify level 8
2025-09-02 21:05:11 - check_target_files_vintf.py - INFO    : stderr: ERROR: files are incompatibl
e: android.hardware.biometrics.fingerprint@2.3::IBiometricsFingerprint/default is deprecated in co
mpatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default
 from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.cas@1.2::IMediaCasService/default is deprecated in compatibility matrix at FCM Ve
rsion 8; it should not be served.
    because it matches android.hardware.cas@1.1::IMediaCasService/default from /system/etc/vintf/c
ompatibility_matrix.6.xml
android.hardware.light@1::ILights/default is deprecated; requires at least 2
    because it matches android.hardware.light.ILights/default (@1) from /system/etc/vintf/compatib
ility_matrix.6.xml
android.hardware.sensors@2.1::ISensors/default is deprecated in compatibility matrix at FCM Versio
n 8; it should not be served.
    because it matches android.hardware.sensors@2.0::ISensors/default from /system/etc/vintf/compa
tibility_matrix.6.xml
android.hardware.biometrics.fingerprint@2.3::IBiometricsFingerprint/default is deprecated in compa
tibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default
 from /system/etc/vintf/compatibility_matrix.7.xml
android.hardware.cas@1.2::IMediaCasService/default is deprecated in compatibility matrix at FCM Ve
rsion 8; it should not be served.
    because it matches android.hardware.cas@1.1::IMediaCasService/default from /system/etc/vintf/c
ompatibility_matrix.7.xml
android.hardware.light@1::ILights/default is deprecated; requires at least 2
    because it matches android.hardware.light.ILights/default (@1) from /system/etc/vintf/compatib
ility_matrix.7.xml
android.hardware.sensors@2.1::ISensors/default is deprecated in compatibility matrix at FCM Versio
n 8; it should not be served.
    because it matches android.hardware.sensors@2.0::ISensors/default from /system/etc/vintf/compa
tibility_matrix.7.xml
android.hardware.biometrics.fingerprint@2.3::IBiometricsFingerprint/default is deprecated in compa
tibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default
 from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.cas@1.2::IMediaCasService/default is deprecated in compatibility matrix at FCM Ve
rsion 8; it should not be served.
    because it matches android.hardware.cas@1.1::IMediaCasService/default from /system/etc/vintf/c
ompatibility_matrix.5.xml
android.hardware.light@1::ILights/default is deprecated; requires at least 2
    because it matches android.hardware.light.ILights/default (@1) from /system/etc/vintf/compatib
ility_matrix.5.xml
android.hardware.sensors@2.1::ISensors/default is deprecated in compatibility matrix at FCM Versio
n 8; it should not be served.
    because it matches android.hardware.sensors@2.0::ISensors/default from /system/etc/vintf/compa
tibility_matrix.5.xml: Success

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/lahaina/workspace1/2by2/out/host/linux-x86/bin/ota_from_target_files/__main__.py", l
ine 45, in <module>
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "ota_from_target_files.py", line 1574, in <module>
  File "ota_from_target_files.py", line 1545, in main
  File "ota_from_target_files.py", line 1069, in GenerateAbOtaPackage
  File "check_target_files_vintf.py", line 303, in CheckVintfIfTrebleEnabled
RuntimeError: VINTF compatibility check failed
21:05:11 ninja failed with: exit status 1